name: ci-branch
env:
  NODE_VERSION: "20"
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm test -- --run
